sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -e .
- pip install pep8
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
script:
- pep8 --exclude=uw_nws/tests uw_nws
- coverage run uw_nws/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_nws/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_nws/VERSION
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: uw-it-axdd
  skip_cleanup: true
  password:
    secure: ZmxWBJcWt/6gL+/gK0uywv9JluVDdvV8cAXtA59ssfGURRE4B1cQcy4qx/2CHLorRSn4bdOoZ7AamMk5EVrYVl4YslBBIc8Jn0pU3YEdEt9RWM6IzcfZuqmFYGQvCG2eSOmWfgxch81Yqv0kY74v+s5NntPz9AjlOvYzuPmRgu2z9p3kxj5CugtGi9/9ctFlEL36jCJbTxq4l5E1x4nMGHf0ib2+0sv6ye00JGDZtcxw0Ns49G1gdHs02WuQGufzOdGwmYumjih+rZt7nm6/jrPpPC1/ZqiqrVqjlSBspraxYxiBzLKvL6e9rEZfBDbgFVvf6ObgfbGr+yS09jpubd4QTLjwEArAliriXbVUJkr4ft7mrKSPBetUv10bRztstXij2NtgRQlQgBOQC0ASF8jQdKSjKuD1/z9QtBn7KG/sGIEoXCxgPVkNiLV5o8vwQhlEbf8k1WIJKRCAxLetN5MRpxvflQGCoW7ABOkYSQonxTTA2F5Ty2DGF2E5fjBsryScn106cYPuSVAJpMZGRyUtAsKIyxyJ1imMlYvgNncu/0dPSH60OiOcO9pZwGcqKmvabzdBvSV3jA+eka2IAUSo8dEYLS5nSaFQfYxA5V8r5wUL4zJTTdZLhOiDETG3JyFCaxtDl44YONe5AwG2booZdyI7dqSSJ1cR5wIYDsU=
  on:
    tags: true
    python: '3.5'
